# Generated by Django 2.0.5 on 2018-05-12 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_substitute', '0002_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmarks',
        ),
    ]
