# Generated by Django 2.0.5 on 2018-05-12 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_substitute', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
